import { StyleSheet } from 'react-native';

const colors = {
  ink900: '#1a1f1a',
  ink700: '#2f3a2f',
  ink500: '#4a5a4a',
  muted300: '#9aa39a',
  sand50: '#f7f4ee',
  sand100: '#efe8dd',
  sand200: '#e4dccf',
  leaf400: '#7aa77b',
};

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.sand50,
  },
  content: {
    padding: 20,
    paddingBottom: 40,
  },
  hero: {
    backgroundColor: '#fff',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.sand200,
    padding: 20,
  },
  heroKicker: {
    fontSize: 12,
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: colors.ink500,
  },
  heroTitle: {
    fontSize: 22,
    fontWeight: '600',
    color: colors.ink900,
    marginTop: 8,
  },
  heroCopy: {
    marginTop: 8,
    color: colors.ink700,
    fontSize: 13,
    lineHeight: 18,
  },
  heroBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 12,
  },
  badge: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 999,
    fontSize: 11,
    marginRight: 8,
    marginBottom: 8,
    color: colors.ink700,
    backgroundColor: '#eef2ec',
  },
  badgeDemo: {
    backgroundColor: '#f5ede1',
    color: '#5b4823',
  },
  badgeSignedOut: {
    backgroundColor: '#e2edf5',
    color: '#2c4a5e',
  },
  heroProgressCard: {
    marginTop: 12,
    backgroundColor: '#fff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.sand200,
    padding: 14,
  },
  heroProgressLabel: {
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 2,
    color: colors.ink500,
  },
  heroProgressMeta: {
    marginTop: 6,
    fontSize: 12,
    color: colors.ink700,
  },
  progressTrack: {
    width: '100%',
    height: 8,
    backgroundColor: '#e7e1d6',
    borderRadius: 999,
    overflow: 'hidden',
    marginTop: 10,
  },
  progressFill: {
    height: '100%',
    backgroundColor: colors.leaf400,
  },
  summaryRow: {
    marginTop: 18,
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -8,
  },
  summaryCard: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.sand200,
    marginHorizontal: 8,
    marginBottom: 16,
    flexBasis: 220,
    flexGrow: 1,
  },
  summaryLabel: {
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 1,
    color: colors.ink500,
  },
  summaryValue: {
    fontSize: 20,
    fontWeight: '600',
    color: colors.ink900,
    marginTop: 6,
  },
  summaryMeta: {
    color: colors.ink500,
    fontSize: 12,
    marginTop: 4,
  },
  sectionHeader: {
    marginTop: 8,
    marginBottom: 10,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: colors.ink900,
  },
  sectionSubtitle: {
    marginTop: 4,
    color: colors.ink700,
    fontSize: 12,
    lineHeight: 17,
  },
  habitatGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -8,
  },
  habitatCard: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.sand200,
    marginHorizontal: 8,
    marginBottom: 16,
    flexBasis: 240,
    flexGrow: 1,
  },
  habitatHeader: {
    marginBottom: 10,
  },
  habitatTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  habitatIcon: {
    fontSize: 20,
    marginRight: 8,
  },
  habitatName: {
    fontSize: 15,
    fontWeight: '600',
    color: colors.ink900,
  },
  habitatState: {
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 1,
    color: colors.ink500,
  },
  habitatDescription: {
    marginTop: 6,
    fontSize: 12,
    color: colors.ink700,
    lineHeight: 17,
  },
  habitatStatsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  habitatStat: {
    fontSize: 12,
    color: colors.ink500,
  },
  habitatNext: {
    marginTop: 8,
    fontSize: 12,
    color: colors.ink700,
    backgroundColor: '#f8f5ee',
    borderRadius: 10,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  journalList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginHorizontal: -8,
  },
  journalItem: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.sand200,
    marginHorizontal: 8,
    marginBottom: 16,
    flexBasis: 220,
    flexGrow: 1,
  },
  journalName: {
    fontWeight: '600',
    color: colors.ink900,
  },
  journalMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    marginTop: 6,
  },
  journalHabitat: {
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 1,
    color: colors.ink500,
    marginRight: 8,
  },
  journalDate: {
    fontSize: 11,
    color: colors.ink700,
    marginRight: 8,
  },
  journalBadge: {
    fontSize: 10,
    color: '#316940',
    backgroundColor: '#e3f1e6',
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 999,
  },
  primaryButton: {
    marginTop: 8,
    backgroundColor: colors.ink900,
    borderRadius: 999,
    paddingVertical: 12,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 13,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
});
